#define VERSION_MAJOR 2
#define VERSION_MINOR 2
#define VERSION_BUILD 0
#define VERSION_QFE 0
#define VERSION_BUILD_DATE "02/12/2015"
#define VERSION_BUILD_TIME "18:00:00UTC"

#define _STR(x) #x
#define STR(x) _STR(x)

#define VERSION_NUMBER VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_QFE
#define VERSION_STRING STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_BUILD) "." STR(VERSION_QFE)
#define VERSION_PRINT "v" STR(VERSION_MAJOR) "." STR(VERSION_MINOR) " build " STR(VERSION_BUILD)
#define VERSION_COMPANY ""
#define VERSION_COPYRIGHT "(C) Gugulea 2005"
#define VERSION_TRADEMARK ""
#define VERSION_BUILD_DATE_TIME VERSION_BUILD_DATE " - " VERSION_BUILD_TIME
